# Generated by Django 4.2.6 on 2023-10-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_author_blogpage_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
